schema_version = "1.0.0"
id = "messythings"
version = "1.5.0"
name = "Messy Things"
tagline = "Deal with badly organized projects"
maintainer = "Mikhail Rachinskiy"
type = "add-on"
tags = ["Scene", "Object"]
blender_version_min = "4.2.0"
website = "https://github.com/mrachinskiy/messythings"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2017-2024 Mikhail Rachinskiy"]
